//! Out-of-band **pairing code** — a copyable string that carries a peer's
//! identity (its TLS leaf-cert fingerprint) plus routable candidate addresses,
//! so two machines that can't find each other on the LAN (different subnets, no
//! mDNS) can still pair: a human carries the code across. Because it carries the
//! real fingerprint, the sender's first dial is pinned + MITM-resistant.
//!
//! This is NOT the wire protocol (see `hops-proto`) — it never touches a socket.
//! It is generated by the receiver from its own fingerprint + addresses and
//! pasted into the sender, which seeds a *provisional* device and routes the
//! first connection through the approval sheet. Pasting a code is never, on its
//! own, a grant of trust — it only pre-fills the identity to confirm.
//!
//! `decode` treats its input as hostile (a pasted string): it rejects a wrong
//! prefix, corrupt payload, a malformed fingerprint, or out-of-bounds sizes, and
//! sanitizes the advisory label before it is ever rendered or logged.

use std::net::SocketAddr;

use base64::Engine;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use serde::{Deserialize, Serialize};

/// Versioned, human-recognizable prefix. Bump the suffix on a breaking payload
/// change so an older client rejects a newer code cleanly instead of mis-parsing.
const PREFIX: &str = "hops-pair-1.";

/// Caps on decoded, attacker-influenced fields.
const MAX_LABEL_LEN: usize = 64;
const MAX_ADDRS: usize = 8;
/// Hard cap on the pasted string itself, so a pathologically large paste can't
/// drive a big base64 + json allocation. A real code (8 addrs + label) is well
/// under 1 KB.
const MAX_CODE_LEN: usize = 4096;
/// A leaf-cert SHA-256 fingerprint is 32 lowercase hex bytes joined by ':'.
const FINGERPRINT_GROUPS: usize = 32;

/// The decoded contents of a pairing code.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PairingCode {
    /// The generator's TLS leaf-cert fingerprint (`aa:bb:..`, 32 groups) — the
    /// trust anchor, byte-identical to the `authorized_fingerprints` key.
    pub fingerprint: String,
    /// Routable candidate addresses to dial (each carries its own port).
    pub addrs: Vec<SocketAddr>,
    /// A suggested display name; advisory only — the user confirms/edits it.
    pub label: String,
}

#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum PairingError {
    #[error("not a hops pairing code")]
    BadPrefix,
    #[error("corrupt pairing code")]
    Corrupt,
    #[error("pairing code has an invalid fingerprint")]
    BadFingerprint,
    #[error("pairing code is out of bounds")]
    OutOfBounds,
}

/// True iff `fp` is a lowercase, colon-separated 32-byte hex fingerprint — the
/// exact shape used as the allowlist key. Rejects uppercase / short / non-hex so
/// a pasted code can't smuggle in a bogus identity string.
/// Canonicalise a fingerprint arriving from ANY untrusted door — the IPC
/// channel, the CLI, a hand-edited config — into the one form the rest of the
/// system compares against, or reject it.
///
/// Computed leaf-cert fingerprints are lowercase `aa:bb:..`. Two of our own
/// hardening commits once disagreed about where that normalisation happens:
/// `Config::authorized_fingerprints` lowercased on READ while the revocation
/// tombstone was looked up case-SENSITIVELY, so re-authorizing an expelled
/// fingerprint with `A-F` uppercased missed the tombstone, and the next config
/// read folded it back to canonical form. The expelled device was trusted
/// again. Neither commit was wrong on its own; they were wrong together
/// (issue #67).
///
/// So: normalise where a fingerprint ENTERS the system, never at each reader.
pub fn canonical_fingerprint(fp: &str) -> Option<String> {
    let lowered = fp.trim().to_lowercase();
    valid_fingerprint(&lowered).then_some(lowered)
}

pub fn valid_fingerprint(fp: &str) -> bool {
    let mut groups = 0usize;
    for g in fp.split(':') {
        groups += 1;
        let bytes = g.as_bytes();
        if bytes.len() != 2
            || !bytes
                .iter()
                .all(|&b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
        {
            return false;
        }
    }
    groups == FINGERPRINT_GROUPS
}

/// Strip control / bidi / zero-width characters and clamp length — the label is
/// attacker-influenced and gets rendered + logged, so defeat homoglyph/bidi
/// spoofing of a trusted name.
pub fn sanitize_label(s: &str) -> String {
    s.chars()
        .filter(|c| {
            !c.is_control()
                && !matches!(*c,
                    '\u{200b}'..='\u{200f}'   // zero-width + LRM/RLM
                    | '\u{202a}'..='\u{202e}' // bidi embeddings/overrides
                    | '\u{2066}'..='\u{2069}' // bidi isolates
                    | '\u{feff}') // BOM / zero-width no-break
        })
        .take(MAX_LABEL_LEN)
        .collect()
}

impl PairingCode {
    /// Encode to a copyable string: `hops-pair-1.<base64url-nopad(json)>`
    /// (URL-safe, unpadded — survives double-click select + paste).
    pub fn encode(&self) -> String {
        let json = serde_json::to_vec(self).expect("pairing code serializes");
        format!("{PREFIX}{}", URL_SAFE_NO_PAD.encode(json))
    }

    /// Decode + validate an untrusted pasted string. Rejects a wrong prefix,
    /// corrupt base64/json, a malformed fingerprint, or an empty / oversized
    /// address list; sanitizes the label. A successful decode is NOT trust — the
    /// caller still routes it through the approval sheet.
    pub fn decode(s: &str) -> Result<Self, PairingError> {
        if s.len() > MAX_CODE_LEN {
            return Err(PairingError::OutOfBounds);
        }
        let body = s
            .trim()
            .strip_prefix(PREFIX)
            .ok_or(PairingError::BadPrefix)?;
        let bytes = URL_SAFE_NO_PAD
            .decode(body)
            .map_err(|_| PairingError::Corrupt)?;
        let mut code: PairingCode =
            serde_json::from_slice(&bytes).map_err(|_| PairingError::Corrupt)?;
        if !valid_fingerprint(&code.fingerprint) {
            return Err(PairingError::BadFingerprint);
        }
        if code.addrs.is_empty() || code.addrs.len() > MAX_ADDRS {
            return Err(PairingError::OutOfBounds);
        }
        code.label = sanitize_label(&code.label);
        Ok(code)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fp() -> String {
        vec!["aa"; FINGERPRINT_GROUPS].join(":")
    }

    fn code(label: &str) -> PairingCode {
        PairingCode {
            fingerprint: fp(),
            addrs: vec!["10.110.20.42:4242".parse().unwrap()],
            label: label.to_string(),
        }
    }

    #[test]
    fn round_trips() {
        let c = code("studio-mac");
        let s = c.encode();
        assert!(s.starts_with(PREFIX));
        assert_eq!(PairingCode::decode(&s).unwrap(), c);
    }

    #[test]
    fn round_trips_with_whitespace_and_multiple_addrs() {
        let c = PairingCode {
            fingerprint: fp(),
            addrs: vec![
                "10.110.20.42:4242".parse().unwrap(),
                "[fe80::1]:4242".parse().unwrap(),
            ],
            label: "rig".into(),
        };
        let s = format!("  {}\n", c.encode());
        assert_eq!(PairingCode::decode(&s).unwrap(), c);
    }

    #[test]
    fn rejects_bad_prefix() {
        assert_eq!(
            PairingCode::decode("nope").unwrap_err(),
            PairingError::BadPrefix
        );
        assert_eq!(
            PairingCode::decode("hops-pair-2.abc").unwrap_err(),
            PairingError::BadPrefix
        );
    }

    #[test]
    fn rejects_corrupt_body() {
        assert_eq!(
            PairingCode::decode("hops-pair-1.!!!not-base64!!!").unwrap_err(),
            PairingError::Corrupt
        );
        // valid base64 of non-json
        let b = URL_SAFE_NO_PAD.encode(b"not json at all");
        assert_eq!(
            PairingCode::decode(&format!("{PREFIX}{b}")).unwrap_err(),
            PairingError::Corrupt
        );
    }

    #[test]
    fn rejects_bad_fingerprint() {
        for bad in ["AA:BB", "zz:zz", "aa", &vec!["aa"; 31].join(":")] {
            let c = PairingCode {
                fingerprint: bad.to_string(),
                addrs: vec!["10.0.0.1:4242".parse().unwrap()],
                label: "x".into(),
            };
            assert_eq!(
                PairingCode::decode(&c.encode()).unwrap_err(),
                PairingError::BadFingerprint,
                "should reject fingerprint {bad:?}"
            );
        }
    }

    #[test]
    fn rejects_empty_or_oversized_addrs() {
        let mut c = code("x");
        c.addrs.clear();
        assert_eq!(
            PairingCode::decode(&c.encode()).unwrap_err(),
            PairingError::OutOfBounds
        );
        let mut c = code("x");
        c.addrs = (0..MAX_ADDRS + 1)
            .map(|i| format!("10.0.0.{}:4242", i + 1).parse().unwrap())
            .collect();
        assert_eq!(
            PairingCode::decode(&c.encode()).unwrap_err(),
            PairingError::OutOfBounds
        );
    }

    #[test]
    fn sanitizes_label_control_and_bidi() {
        let c = code("stu\u{202e}dio\u{200b}\tpc");
        let decoded = PairingCode::decode(&c.encode()).unwrap();
        assert_eq!(decoded.label, "studiopc");
    }

    #[test]
    fn rejects_oversized_input() {
        let huge = format!("{PREFIX}{}", "A".repeat(MAX_CODE_LEN));
        assert_eq!(
            PairingCode::decode(&huge).unwrap_err(),
            PairingError::OutOfBounds
        );
    }

    #[test]
    fn clamps_overlong_label() {
        let c = code(&"n".repeat(200));
        let decoded = PairingCode::decode(&c.encode()).unwrap();
        assert_eq!(decoded.label.chars().count(), MAX_LABEL_LEN);
    }
}

#[cfg(test)]
mod canonical_fingerprint_tests {
    use super::*;

    fn fp(case: fn(&str) -> String) -> String {
        case(
            &(0..32)
                .map(|i| format!("{:02x}", i))
                .collect::<Vec<_>>()
                .join(":"),
        )
    }

    #[test]
    fn uppercase_and_lowercase_spellings_canonicalise_to_the_same_string() {
        let lower = fp(|s| s.to_string());
        let upper = fp(|s| s.to_uppercase());
        assert_ne!(lower, upper, "precondition: the two spellings differ");
        assert_eq!(
            canonical_fingerprint(&upper),
            canonical_fingerprint(&lower),
            "an uppercased fingerprint must not be a different identity — that is issue #67"
        );
        assert_eq!(canonical_fingerprint(&upper), Some(lower));
    }

    #[test]
    fn canonicalisation_is_idempotent() {
        let c = canonical_fingerprint(&fp(|s| s.to_uppercase())).expect("valid");
        assert_eq!(canonical_fingerprint(&c), Some(c.clone()));
    }

    #[test]
    fn junk_is_rejected_rather_than_normalised() {
        for bad in [
            "",
            "not-a-fingerprint",
            "00:01",
            &fp(|s| s.to_string())[..90],
            "zz:01",
        ] {
            assert_eq!(canonical_fingerprint(bad), None, "must reject {bad:?}");
        }
    }
}

/// How many digits the verification code has. Six is the ceiling on what a
/// person will reliably compare across two screens, and it is what SSH,
/// Bluetooth SSP and Signal all settled on.
pub const SAS_DIGITS: usize = 6;

/// A short number BOTH machines display, for a human to compare.
///
/// # Why this exists
///
/// Every path into hops' trust store today ends at a prompt on ONE machine.
/// That prompt can be caused by something other than the person sitting there:
/// anything holding the IPC token can make the daemon dial an address it chose
/// and raise a genuine approval prompt for a fingerprint it chose (#61). The
/// prompt is real; its provenance is forged. Labelling it (#129) tells a
/// careful human something is odd — it does nothing for a machine check.
///
/// A number derived from BOTH fingerprints and shown on BOTH screens is
/// different in kind. A compromised console cannot make the *other* machine's
/// screen display a number of its choosing, so "the same six digits appear over
/// there" is evidence no local attacker can manufacture. That is the
/// out-of-band human act #61 step 2 needs before "only an unsolicited attempt
/// may admit a grant" is implementable — today it is not, because approving an
/// outbound dial is the only way to pair at all.
///
/// # Properties
///
/// - **Symmetric.** The inputs are sorted, so both ends compute the same digits
///   without agreeing who is "first".
/// - **Neither side chooses it.** It commits to both fingerprints, so a machine
///   that picks its own key to force a value must also control the peer's.
/// - **Not a secret.** It authenticates nothing on its own and is safe to show.
///   Its whole job is to be compared by a person.
///
/// Returns `None` if either fingerprint is not a valid one — a code derived
/// from a malformed input would be a number that means nothing.
pub fn verification_code(a: &str, b: &str) -> Option<String> {
    use sha2::{Digest, Sha256};
    let (a, b) = (canonical_fingerprint(a)?, canonical_fingerprint(b)?);
    // Sorted so the two ends agree without negotiating an order.
    let (lo, hi) = if a <= b { (a, b) } else { (b, a) };
    let mut h = Sha256::new();
    // Domain separation: this hash must never collide with any other use of a
    // fingerprint pair elsewhere in hops.
    h.update(b"hops-pairing-verification-v1");
    h.update(lo.as_bytes());
    h.update(b"\0");
    h.update(hi.as_bytes());
    let d = h.finalize();
    // 8 bytes is far more entropy than 10^6 needs; the modulo bias across a
    // 64-bit value reduced to a million buckets is not measurable by a human
    // comparing digits, and this is a comparison aid, not a key.
    let n = u64::from_be_bytes(d[..8].try_into().ok()?);
    Some(format!(
        "{:0width$}",
        n % 10u64.pow(SAS_DIGITS as u32),
        width = SAS_DIGITS
    ))
}

#[cfg(test)]
mod verification_code_tests {
    use super::*;

    const A: &str = "aa:bb:cc:dd:ee:ff:00:11:22:33:44:55:66:77:88:99:\
aa:bb:cc:dd:ee:ff:00:11:22:33:44:55:66:77:88:99";
    const B: &str = "11:22:33:44:55:66:77:88:99:aa:bb:cc:dd:ee:ff:00:\
11:22:33:44:55:66:77:88:99:aa:bb:cc:dd:ee:ff:00";

    /// The whole ceremony rests on this: both machines must show the same
    /// digits without negotiating who is "first".
    #[test]
    fn both_ends_compute_the_same_code() {
        assert_eq!(
            verification_code(A, B),
            verification_code(B, A),
            "the code must not depend on which machine computes it, or the two \
             screens disagree and the user is told to reject a valid pairing"
        );
    }

    #[test]
    fn it_is_six_digits() {
        let c = verification_code(A, B).expect("valid fingerprints");
        assert_eq!(c.len(), SAS_DIGITS);
        assert!(c.chars().all(|ch| ch.is_ascii_digit()), "got {c:?}");
    }

    /// Leading zeros must survive. `042315` truncated to `42315` is a different
    /// number on the other screen, and the user is told to reject a good pair.
    #[test]
    fn leading_zeros_are_kept() {
        // search for a pair that produces a leading zero, then assert the width
        let mut found = false;
        for i in 0..4096u32 {
            let b = format!("{:02x}", i % 256);
            let fp = std::iter::repeat(b).take(32).collect::<Vec<_>>().join(":");
            if let Some(c) = verification_code(A, &fp) {
                assert_eq!(c.len(), SAS_DIGITS, "width must be fixed: {c:?}");
                if c.starts_with('0') {
                    found = true;
                    break;
                }
            }
        }
        assert!(
            found,
            "expected to find a code with a leading zero in 4096 tries"
        );
    }

    /// A different peer must produce a different number, or the code proves
    /// nothing about WHO is on the other side.
    ///
    /// Tested with a peer that sorts BELOW us and one that sorts ABOVE us. The
    /// inputs are sorted before hashing, so varying only one side exercises
    /// only one slot — an implementation that hashed `lo` and ignored `hi`
    /// passed a single-direction version of this test.
    #[test]
    fn a_different_peer_gives_a_different_code_in_either_slot() {
        let below = "00:".repeat(31) + "00";
        let below2 = "00:".repeat(31) + "01";
        assert_ne!(
            verification_code(A, &below).unwrap(),
            verification_code(A, &below2).unwrap(),
            "a peer sorting BELOW us must still change the code"
        );
        let above = "ff:".repeat(31) + "f0";
        let above2 = "ff:".repeat(31) + "f1";
        assert_ne!(
            verification_code(&below, &above).unwrap(),
            verification_code(&below, &above2).unwrap(),
            "a peer sorting ABOVE us must change the code — otherwise the hash \
             commits to one identity and the number says nothing about who is \
             actually on the other end"
        );
    }

    /// Case is not identity — the trust maps are canonicalised for exactly this
    /// reason (#67/#100), and a code that disagreed across case would tell the
    /// user two honest machines do not match.
    #[test]
    fn case_does_not_change_the_code() {
        assert_eq!(
            verification_code(A, B),
            verification_code(&A.to_uppercase(), B),
            "an uppercased fingerprint is the same identity, so the same code"
        );
    }

    /// A code from a malformed fingerprint would be a number that means
    /// nothing, displayed as though it meant something.
    #[test]
    fn a_malformed_fingerprint_yields_no_code() {
        for bad in ["", "nonsense", "aa:bb", &"zz:".repeat(32)] {
            assert!(
                verification_code(A, bad).is_none(),
                "{bad:?} must not produce a code"
            );
            assert!(
                verification_code(bad, A).is_none(),
                "{bad:?} in either slot"
            );
        }
    }
}
